### ISSUE TITLE
Can't resolve dependencies due instalation

### ISSUE THREAD

**Issue by abyssmemes** [archcraft-os/archcraft-newm#1]
loading packages...
resolving dependencies...
warning: cannot resolve "newm-git", a dependency of "archcraft-newm"
:: The following package cannot be upgraded due to unresolvable dependencies:
      archcraft-newm

:: Do you want to skip the above package for this upgrade? [y/N] y
looking for conflicting packages...
 there is nothing to do

**Comment by abyssmemes** [comment]
I making installation on Archcraft the latest version

**Comment by adi1090x** [comment]
Update your pacman database with `sudo pacman -Syy`
