### ISSUE TITLE
arch linux faces some troubles

### ISSUE THREAD

**Issue by cynosure279** [archcraft-os/archcraft-newm#12]

**Comment by cynosure279** [comment]
i use arch linux（with kde5 and sddm）
then i bought the package yesterday（thank you for your work！），however，when i install it，i found that there is something wrong with icons（they can not be displayed ）and most importantly，my network manager can not work properly（it just says that my network is activied but it is not in fact）
when i use kde（log out to use it），it works well.

**Comment by adi1090x** [comment]
For icons, you need to install the provided fonts. and About network manager, Archcraft NEWM has nothing to do with the configs of network manager on your system. these are just config file for NEWM in particular. Make sure you have NetworkManager installed on your system and the service is active and running.
