### ISSUE TITLE
Lockscreen Not Working

### ISSUE THREAD

**Issue by joselevelsup** [archcraft-os/archcraft-newm#2]
Hey @adi1090x ,

First off I am a big fan of your rices. I could never do it myself cause it's just to tedious. So I kind of rely on other's rices and just tweak it. 

So I installed your rice for this WM. The lockscreen just locks after a certain amount of time (which I don't care) but there is no way for me to unlock it. I would have to open another TTY and run `newm-cmd unlock`. In your videos and screenshots, I notice there should be a pop up. Any possible reason why this wouldn't work?

**Comment by adi1090x** [comment]
@joselevelsup 

make sure you have `alacritty` terminal and `thefuzz` python module installed.

to install the module, run : `pip3 install thefuzz`

you can adjust the power settings in this section of `config.py` file
```python
## Power Saving ────────────────────────────────────────────────────────────
energy = {
    'idle_callback': lambda event: "idle",
    'idle_times': [120, 300, 600],
    'suspend_command': "systemctl suspend",
}
```
120 is the time to dim the screen, 300 is the time to lock and 600 is the time to suspend/sleep.

**Comment by joselevelsup** [comment]
I installed the `thefuzz` and I already had `alacritty` installed. Still nothing to prompt me to unlock.

**Comment by adi1090x** [comment]
@joselevelsup So, You're still not getting this?

![newm_4](https://user-images.githubusercontent.com/26059688/176843831-b8bde71c-1a55-4221-8f46-81b32dd66a97.png)

Which distro are you using? 

Login to NEWM and manually lock the screen. then unlock it the way you're unlocking it. then paste the content of `~/.cache/newm_log` file here.

**Comment by joselevelsup** [comment]
@adi1090x  sorry for the late response. 

Yeah, I'm not getting that at all. I lock my screen and just type my password but nothing (I thought it might be hidden or something). 

Here is my [newm_log](https://pastebin.com/vZYUeakQ)

Let me know if you need anything else. 

EDIT: Forgot to mention my distro is Manjaro

**Comment by hekatonkheirex** [comment]
It looks like it's the wm issue, as reported [here](https://github.com/jbuchermn/newm/issues/98#issuecomment-1186071016)

I have installed this dotfiles too. System is `5.18.14-arch1-1`. Sway and River runs fine.

**Comment by adi1090x** [comment]
So, Not resolved?
With alacritty and thefuzz module, it works.

**Comment by hekatonkheirex** [comment]
I'm sorry for late reply, but this is the message I got when I try to type the password https://imgur.com/jvbCZN3
I have foot, alacritty and thefuzz installed

**Comment by joselevelsup** [comment]
Yeah still nothing on my end. I have all the modules installed and I still can't figure it out. Then again, python is not my strong suit lol.

**Comment by adi1090x** [comment]
Fixed by adding `python-thefuzz` pkg in Repo. Update!
