### ISSUE TITLE
Cant change keyboard layout 

### ISSUE THREAD

**Issue by Perchant76** [archcraft-os/archcraft-newm#4]
After using:
`localectl set-keymap sk-qwertz`
After using:
`localectl status`
SHOWED THIS:
   System Locale: LANG=en_US.UTF-8
                  LC_NUMERIC=sk_SK.UTF-8
                  LC_TIME=sk_SK.UTF-8
                  LC_MONETARY=sk_SK.UTF-8
                  LC_PAPER=sk_SK.UTF-8
                  LC_NAME=sk_SK.UTF-8
                  LC_ADDRESS=sk_SK.UTF-8
                  LC_TELEPHONE=sk_SK.UTF-8
                  LC_MEASUREMENT=sk_SK.UTF-8
                  LC_IDENTIFICATION=sk_SK.UTF-8
       VC Keymap: sk-qwertz
      X11 Layout: sk

It is somehow unable to change keyboard layout to `sk-qwertz`
Note: It changed keyboard in any other VMs, but its not working in `archcraft-newm`

**Comment by c-leri** [comment]
I found a solution !
Go in your ~/.config/newm/config.py and there edit line 105 and set "xbd_layout" to the keyboard layout you want to use

**Comment by adi1090x** [comment]
Yes, That's how you can change the layout in newm.

Edit file : ` ~/.config/newm/config.py` and lines 102..105

```python
pywm = {
    'xkb_model': "",
    'xkb_layout': "",
    'xkb_variant': "",
    'xkb_options': "",
}
```
